### ISSUE TITLE
用户Token过期异常

### ISSUE THREAD

**Issue by zhangran25** [wxiaoqi/Spring-Cloud-Platform#39]
请问，前后端及所需环境都安装好并启动进程后，都是按照顺序启动的，报错：用户Token过期异常。具体日志如下，这个请问具体是怎么处理？多谢指导！

2020-09-30 16:33:31.120  INFO [ace-gateway,50f8512ec9f1194c,50f8512ec9f1194c,false] 2992 --- [ctor-http-nio-2] c.g.w.s.gate.filter.AccessGatewayFilter  : check token and user permission....
2020-09-30 16:33:31.123 ERROR [ace-gateway,50f8512ec9f1194c,50f8512ec9f1194c,false] 2992 --- [ctor-http-nio-2] c.g.w.s.gate.filter.AccessGatewayFilter  : 用户Token过期异常

java.lang.NullPointerException: value
	at io.netty.util.internal.ObjectUtil.checkNotNull(ObjectUtil.java:33) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.handler.codec.DefaultHeaders.addObject(DefaultHeaders.java:327) ~[netty-codec-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.handler.codec.http.DefaultHttpHeaders.add(DefaultHttpHeaders.java:117) ~[netty-codec-http-4.1.31.Final.jar:4.1.31.Final]

**Comment by LuckAx** [comment]
你可能发错邮件了，我这边仓库没开过项目Spring-Cloud-Platform




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wxiaoqi/Spring-Cloud-Platform"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月30日(星期三) 下午4:43
收件人:&nbsp;"wxiaoqi/Spring-Cloud-Platform"<Spring-Cloud-Platform@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[wxiaoqi/Spring-Cloud-Platform] 用户Token过期异常 (#39)





 
请问，前后端及所需环境都安装好并启动进程后，都是按照顺序启动的，报错：用户Token过期异常。具体日志如下，这个请问具体是怎么处理？多谢指导！
 
2020-09-30 16:33:31.120  INFO [ace-gateway,50f8512ec9f1194c,50f8512ec9f1194c,false] 2992 --- [ctor-http-nio-2] c.g.w.s.gate.filter.AccessGatewayFilter  : check token and user permission....
 2020-09-30 16:33:31.123 ERROR [ace-gateway,50f8512ec9f1194c,50f8512ec9f1194c,false] 2992 --- [ctor-http-nio-2] c.g.w.s.gate.filter.AccessGatewayFilter  : 用户Token过期异常
 
java.lang.NullPointerException: value
 at io.netty.util.internal.ObjectUtil.checkNotNull(ObjectUtil.java:33) ~[netty-common-4.1.31.Final.jar:4.1.31.Final]
 at io.netty.handler.codec.DefaultHeaders.addObject(DefaultHeaders.java:327) ~[netty-codec-4.1.31.Final.jar:4.1.31.Final]
 at io.netty.handler.codec.http.DefaultHttpHeaders.add(DefaultHttpHeaders.java:117) ~[netty-codec-http-4.1.31.Final.jar:4.1.31.Final]

**Comment by zhangran25** [comment]
没有人遇到过这个问题吗，作者可否回复这个问题呢？

**Comment by LuckAx** [comment]
你好，我不是作者；我这都没这个项目，奇怪的是为啥老是发我邮箱




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wxiaoqi/Spring-Cloud-Platform"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月10日(星期六) 下午4:00
收件人:&nbsp;"wxiaoqi/Spring-Cloud-Platform"<Spring-Cloud-Platform@noreply.github.com&gt;;
抄送:&nbsp;"一点星云"<870525936@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [wxiaoqi/Spring-Cloud-Platform] 用户Token过期异常 (#39)





 
没有人遇到过这个问题吗，作者可否回复这个问题呢？

**Comment by tlchun** [comment]
启动正常了一次,后面全部是token异常

**Comment by zhangran25** [comment]
> 启动正常了一次,后面全部是token异常

哦。。。那这是啥原因？需要交钱？我听到有地方说是因为后端用的是2.0版本，而前端用的是3.0版本就会这样。。。目前还没有核实。

**Comment by zhangran25** [comment]
谢谢大家，此问题已经解决。原因是后端用的是2.0，前端版本用的是3.0，所以。。。。

遇到此问题的同学，可以尝试两边版本一致的情况下启动。多谢！
