### ISSUE TITLE
feign.FeignException$ServiceUnavailable: [503 Service Unavailable] 

### ISSUE THREAD

**Issue by liuyuhui2012** [wxiaoqi/Spring-Cloud-Platform#41]
020-11-02 10:12:21.999  INFO [ace-gateway,,,] 3437 --- [erListUpdater-0] c.netflix.config.ChainedDynamicProperty  : Flipping property: ace-admin.ribbon.ActiveConnectionsLimit to use NEXT property: niws.loadbalancer.availabilityFilteringRule.activeConnectionsLimit = 2147483647
2020-11-02 10:12:22.788 ERROR [ace-gateway,,,] 3437 --- [           main] c.g.w.s.a.c.runner.AuthClientRunner      : 初始化加载用户pubKey失败,1分钟后自动重试!

feign.FeignException$ServiceUnavailable: [503 Service Unavailable] during [POST] to [http://ace-admin/client/userPubKey?clientId=ace-gate&secret=123456] [ServiceAuthFeign#getUserPublicKey(String,String)]: []
	at feign.FeignException.serverErrorStatus(FeignException.java:237) ~[feign-core-10.10.1.jar:na]
	at feign.FeignException.errorStatus(FeignException.java:180) ~[feign-core-10.10.1.jar:na]
	at feign.FeignException.errorStatus(FeignException.java:169) ~[feign-core-10.10.1.jar:na]
	at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:92) ~[feign-core-10.10.1.jar:na]
	at feign.AsyncResponseHandler.handleResponse(AsyncResponseHandler.java:96) ~[feign-core-10.10.1.jar:na]
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:138) ~[feign-core-10.10.1.jar:na]
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:89) ~[feign-core-10.10.1.jar:na]
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100) ~[feign-core-10.10.1.jar:na]
	at com.sun.proxy.$Proxy121.getUserPublicKey(Unknown Source) ~[na:na]
	at com.github.wxiaoqi.security.auth.client.runner.AuthClientRunner.refreshUserPubKey(AuthClientRunner.java:43) ~[classes/:na]
	at com.github.wxiaoqi.security.auth.client.runner.AuthClientRunner.run(AuthClientRunner.java:36) ~[classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795) [spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:779) [spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) [spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) [spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at com.github.wxiaoqi.security.gate.GatewayServerBootstrap.main(GatewayServerBootstrap.java:22) [classes/:na]

**Comment by liuyuhui2012** [comment]
The issue is solved.I change the annotation as below:

@FeignClient("${auth.serviceId}")
public interface ServiceAuthFeign {
    @RequestMapping(value = "/client/userPubKey",method = RequestMethod.POST)
    public ObjectRestResponse<byte[]> getUserPublicKey(@RequestParam("clientId") String clientId, @RequestParam("secret") String secret);

}

**Comment by wxiaoqi** [comment]
@liuyuhui2012 OK.
